### ISSUE TITLE
Add symlink task for Atrium libraries 

### ISSUE THREAD

**Issue by mdeltito** [phase2/generator-gadget#27]
Atrium uses a core patch in order to support profile inheritance, but this inheritance does not influence library discovery. This needs to be taken into consideration when building a customized profile that extends Atrium, since these libraries within the Atrium profile directory cannot be discovered/loaded from that location.

Typically I have handled this with a custom task to symlink the libraries from the Atrium profile into `sites/all/libraries` like so:

```
// Symlink all OpenAtrium libraries into sites/all.
grunt.config(['symlink', 'oa-libraries'], {
  expand: true,
  cwd: '<%= config.buildPaths.html %>/profiles/openatrium/libraries',
  src: ['*'],
  dest: '<%= config.buildPaths.html %>/sites/all/libraries'
});
```

This could be baked into gadget, but may be require an additional prompt such as "Are you using this distro as a base for a custom profile?". There's also probably an argument for this being too specific of a use-case to include in this project, and might be more appropriate for other generator projects.

**Comment by arithmetric** [comment]
@mdeltito Thanks for reporting this. Since we're building Atrium support into Gadget, I think this is likely appropriate to bake into Gadget's Atrium distro profile.

@grayside Could you comment on approach?

**Comment by grayside** [comment]
I believe there's an alter hook we might bake into the profile to account for the different location. Perhaps @mike-potter has insight on this.

**Comment by grayside** [comment]
Potter confirms he takes the approach of copying libraries along similar lines. The `grunt package` command's dereferencing of symlinks should result in copying for build artifacts, but the symlink should keep our codebase DRY for development.

Since Gadget generates a Gruntfile.js with an auto-loader for bin/grunt/*.js, let's build this into a `bin/grunt/atrium.js` that can be a grab-bag of any atrium-specific grunt tasks or configurations.
